---
- name: "Update apt package"
  become: yes
  become_method: sudo
  apt:
    update_cache: yes
  
- name: "Upgrade package"
  become: yes
  become_method: sudo
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes 

- name: "Install Node.js"
  become: yes
  apt:
    name: nodejs
    state: present
    update_cache: yes
 
- name: "Install NPM"
  become: yes
  apt:
    name: npm
    state: present
    update_cache: yes

- name: "Install PM2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Create a New Directory"
  file:
    path: ~/web
    state: directory

- name: "Install Index Page"
  template:
    src: "files/index.js"
    dest: "~/web/index.js"

- name: Executing node
  shell: |
    pm2 start ~/web/index.js -f